version: "3.9"

services:
  api:
    build: ./api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - OAUTH2_CLIENT_ID=
      - OAUTH2_CLIENT_SECRET=
      - OAUTH2_PROVIDER_URL=
      - LDAP_URL=
      - LDAP_BIND_DN=
      - LDAP_BIND_PASSWORD=
      - SAML_METADATA_URL=
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - api_config:/app/config

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

volumes:
  pgdata:
  api_config:
