site_name: magllama Documentation
nav:
  - Getting Started: docs/getting-started.md
  - Building: docs/building.md
  - Deploying: docs/deploying.md
  - Configuring Authentication: docs/configuring-authentication.md
  - API: docs/api.md
  - Database: docs/database.md
theme:
  name: material
