site_name: magllama Documentation
nav:
  - Getting Started: docs/getting-started.md
  - Building: docs/building.md
  - Deploying: docs/deploying.md
  - Configuring Authentication: docs/configuring-authentication.md
  - API: docs/api.md
  - Database: docs/database.md
theme:
  name: material
plugins:
  - search
  - awesome-pages
extra:
  mermaid:
    version: 10  # Enable built-in Mermaid support in MkDocs Material
  generator: false  # Fix service-worker.js warning
  remote_url: https://<GITHUB_USERNAME>:${@github.com">GITHUB_TOKEN}@github.com/<GITHUB_USERNAME>/<REPO_NAME>.git
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
