site_name: magllama Documentation

nav:
  - Getting Started: getting-started.md
  - Building: building.md
  - Deploying: deploying.md
  - Configuring Authentication: configuring-authentication.md
  - API: api.md
  - Database: database.md

docs_dir: docs

theme:
  name: material

plugins:
  - search
  - awesome-pages

extra:
  mermaid:
    version: 10  # Enable built-in Mermaid support in MkDocs Material
  generator: false  # Fix service-worker.js warning

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
